# Generated by Django 2.2.1 on 2019-06-19 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(db_index=True, unique=True, verbose_name='book_id')),
                ('subject_name', models.CharField(default='', max_length=200, verbose_name='subject_name')),
                ('book_name', models.CharField(default='', max_length=20, verbose_name='book_name')),
                ('serial_number', models.IntegerField(default='', verbose_name='serial_number')),
            ],
        ),
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
