# Generated by Django 2.2.1 on 2019-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_materials',
            name='book_name',
            field=models.CharField(default='', max_length=100, verbose_name='book_name'),
        ),
    ]
