# Generated by Django 2.2.1 on 2019-06-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(db_index=True, unique=True, verbose_name='book_id')),
                ('subject_name', models.CharField(default='', max_length=200, verbose_name='subject_name')),
                ('book_name', models.CharField(default='', max_length=100, verbose_name='book_name')),
                ('serial_number', models.IntegerField(default='', verbose_name='serial_number')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, unique=True, verbose_name='subject')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('topic', models.CharField(max_length=100, verbose_name='topic')),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='dashboard.Study_material')),
            ],
        ),
        migrations.DeleteModel(
            name='Study_materials',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='post',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.Homework'),
        ),
        migrations.AddField(
            model_name='post',
            name='study_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.Study_material'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
