# Generated by Django 2.2.1 on 2019-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190627_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_material',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='study_material',
            name='subjecte',
            field=models.CharField(default='', max_length=200, verbose_name='subject'),
        ),
    ]
