# Generated by Django 2.2.1 on 2019-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190628_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField(db_index=True, unique=True, verbose_name='assignment_id')),
                ('subject', models.CharField(max_length=100, unique=True, verbose_name='subject')),
                ('assignment_name', models.CharField(max_length=100, unique=True, verbose_name='assignment_name')),
                ('teacher_name', models.CharField(max_length=100, unique=True, verbose_name='teacher_name')),
                ('upload_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(default='', max_length=100, verbose_name='class'),
        ),
    ]
