# Generated by Django 2.2.1 on 2019-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190716_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='upload_assignment',
            name='year',
            field=models.CharField(default='', max_length=100, verbose_name='class'),
        ),
    ]
